# Generated by Django 3.2.19 on 2023-11-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingorder',
            name='buy_target',
            field=models.FloatField(default=0),
        ),
    ]
