# Generated by Django 3.2.19 on 2023-12-01 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profitflow', '0003_auto_20231127_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngelaApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_data', models.JSONField()),
                ('response_data', models.JSONField()),
            ],
        ),
    ]
