# Generated by Django 3.2.19 on 2023-12-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitflow', '0004_angelaapilog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingorder',
            name='option_type',
            field=models.CharField(choices=[('CALL', 'CE'), ('PUT', 'PE')], default=('CALL', 'CALL'), max_length=4),
        ),
    ]
