# Generated by Django 3.2.19 on 2023-12-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitflow', '0005_alter_tradingorder_option_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingorder',
            name='option_type',
            field=models.CharField(choices=[('CE', 'CE'), ('PE', 'PE')], default=('CALL', 'CALL'), max_length=4),
        ),
    ]
