# Generated by Django 3.2.19 on 2023-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitflow', '0006_alter_tradingorder_option_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingorder',
            name='strike_type',
            field=models.CharField(choices=[('ATM', 'ATM'), ('ITM', 'ITM'), ('OTM', 'OTM')], default=('STRIKE', 'Strike'), max_length=6),
        ),
    ]
