# Generated by Django 3.2.19 on 2023-12-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profitflow', '0007_alter_tradingorder_strike_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingorder',
            name='stock_name',
            field=models.CharField(choices=[('NIFTY', 'NIFTY'), ('BANKNIFTY', 'BANKNIFTY')], default=('BankNifty', 'BankNifty'), max_length=10),
        ),
    ]
